image:
  prefix: rook
  repository: rook/ceph
  tag: v1.8.6
  pullPolicy: IfNotPresent
crds:
  enabled: true
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
unreachableNodeTolerationSeconds: 5
currentNamespaceOnly: false
annotations: {}
logLevel: INFO
rbacEnable: true
pspEnable: true
csi:
  enableRbdDriver: true
  enableCephfsDriver: true
  enableGrpcMetrics: false
  enableCephfsSnapshotter: true
  enableRBDSnapshotter: true
  enablePluginSelinuxHostMount : false
  rbdFSGroupPolicy: "ReadWriteOnceWithFSType"
  cephFSFSGroupPolicy: "ReadWriteOnceWithFSType"
  enableOMAPGenerator: false
  provisionerReplicas: 2
  allowUnsupportedVersion: false
  forceCephFSKernelClient: true
  volumeReplication:
    enabled: false
  csiAddons:
    enabled: false
enableDiscoveryDaemon: false
cephCommandsTimeoutSeconds: "15"
enableSelinuxRelabeling: true
hostpathRequiresPrivileged: false
disableDeviceHotplug: false
discoverDaemonUdev:
enableOBCWatchOperatorNamespace: true
admissionController:
monitoring:
  enabled: true
